---

- name: Install tools
  hosts: win
  tasks:
    - name: Get hash of available version
      ansible.builtin.script: scripts/get_available_version.ps1
      changed_when: false
      register: available_hash

    - name: Show hash
      ansible.builtin.debug:
        msg: "{{ available_hash.stdout | trim }}"

    - name: Get hash of installed version
      ansible.builtin.script: scripts/get_installed_version.ps1
      changed_when: false
      register: installed_hash

    - name: Show hash
      ansible.builtin.debug:
        msg: "{{ installed_hash.stdout | trim }}"

    - name: Check if update is needed
      ansible.builtin.set_fact:
        is_update_needed: "{{ installed_hash.stdout | trim != available_hash.stdout | trim }}"

    - name: Show if update is needed
      ansible.builtin.debug:
        msg: "{{ is_update_needed }}"

    - name: Install tools
      when: is_update_needed
      block:
        - name: Create c:\tools
          ansible.windows.win_file:
            path: c:\tools
            state: directory

        - name: Download tools.zip
          ansible.windows.win_get_url:
            url: https://bitbucket.org/qurrent/vmwindowstools/raw/master/tools.zip
            dest: C:\Windows\Temp\tools.zip

        - name: Unzip tools.zip
          community.windows.win_unzip:
            src: C:\Windows\Temp\tools.zip
            dest: C:\
            delete_archive: true

        - name: Create shortcut to TotalCommander for all users
          community.windows.win_shortcut:
            description: TotalCommander
            src: C:\tools\totalcmd\totalcmd.exe
            dest: '%Public%\Desktop\TotalCommander.lnk'
            icon: 'C:\tools\totalcmd\totalcmd.exe,0'
            directory: C:\
            hotkey: Ctrl+Alt+T

        - name: Create shortcut to Notepad++ for all users
          community.windows.win_shortcut:
            description: TotalCommander
            src: C:\tools\Notepad++\notepad++.exe
            dest: '%Public%\Desktop\Notepad++.lnk'
            icon: 'C:\tools\Notepad++\notepad++.exe,0'
            directory: C:\
            hotkey: Ctrl+Alt+N

        - name: Add Everyone full control over c:\tools
          ansible.windows.win_acl:
            path: C:\tools
            user: Everyone
            rights: FullControl
            type: allow
            state: present

        - name: Determine installed version
          ansible.builtin.set_fact:
            installed_version: "{{ available_hash.stdout }}"

        - name: Generate version file
          ansible.builtin.template:
            src: templates/tools_version.j2
            dest: c:\tools\version
            mode: "0644"
