---
- name: Uninstall IIS
  hosts: win
  tasks:
    - name: IIS is uninstalled
      ansible.windows.win_feature:
        name: Web-Server
        state: absent

    - name: Reboot to finish uninstall
      ansible.windows.win_reboot:
