---
- name: Ensure IIS webserver is installed
  ansible.windows.win_feature:
    name: Web-Server
    state: present

- name: Deploy default iisstart.htm file
  ansible.win.win_template:
    src: iisstart.j2
    dest: c:\inetpub\wwwroot\iisstart.htm
